@startuml
start

:Install GPS;
  note right
    It`s not Global Positioning System :)
    GPS – Ghast's Positioning System
  end note
  :Open GPS;

partition "Stage 1: Preparation" %lighten(lime, 75) {
  while (Ready to launch?) is (no)
    if (Is the map installed?) is (no) then
      :Insert map;
    else (yes)
      if (Is mark chosen?) is (no) then
        :Choose mark to follow;
      endif
    endif
  endwhile (yes)
}

:Launch ghast to mark;

partition "Stage 2: Flight" #lightcyan {

  while (Flight in progress?) is (yes)
    fork
      if (Player cancelled flight?) then (yes)
        stop
      endif
    fork again
      if (Change altitude?) then (yes)
        :Adjust altitude;
      endif
    end fork
  endwhile (no)
}

stop
@enduml
