@startuml
left to right direction

actor Player as player

rectangle System {
  usecase "Install position system to ghast" as install
  usecase "Insert the map to device" as mapInsert
  usecase "Remove the map from device" as mapRemove
  usecase "Choose the mark to follow" as markSelect
  usecase "Launch ghast to mark" as launch
  usecase "Cancel launch" as cancel
  usecase "Select flight altitude" as altitudeSelect
}

player --> install
player --> mapInsert
player --> mapRemove
player --> altitudeSelect
player --> launch
player --> cancel

launch --> markSelect : <<include>>

@enduml
